import { z } from "zod";
import { seededPick, normKey } from "../heuristics.js";
import { PROMO_FOOTER } from "../footer.js";

export const DocumentChecklistInput = z.object({
  application_type: z.enum([
    "H-1B", "L-1", "O-1",
    "EB-1A", "EB-1B", "EB-1C",
    "EB-2-NIW",
    "F-1", "K-1",
    "I-485", "naturalization",
    "DACA", "TPS",
  ]).describe("Type of immigration application"),
});

type ApplicationProfile = {
  official_form: string;
  filing_fee_note: string;
  document_checklist: string[];
  common_denial_reasons: string[];
  tips_for_strong_application: string[];
  processing_time_estimate: string;
  premium_processing_available: boolean;
};

const APPLICATION_PROFILES: Record<string, ApplicationProfile> = {
  "H-1B": {
    official_form: "I-129 (Petition for Nonimmigrant Worker)",
    filing_fee_note: "See fee_calculator tool for current USCIS fees",
    document_checklist: [
      "Form I-129 completed and signed by employer",
      "Form I-129 H Classification Supplement",
      "Labour Condition Application (LCA) certified by DOL",
      "Job offer letter specifying position, salary, and duties",
      "Educational credentials: degree certificates, transcripts (official copies)",
      "Credential evaluation report if degree is from a foreign institution (NACES member evaluator)",
      "Beneficiary's passport (valid for at least 6 months beyond intended stay)",
      "Prior immigration documents (copy of current visa, I-94, prior petitions)",
      "Evidence of employer's ability to pay prevailing wage (tax returns, financial statements)",
      "Support letter detailing specialty occupation requirements",
      "If cap-exempt: documentation of qualifying employer status (university, nonprofit, research org)",
    ],
    common_denial_reasons: [
      "Position does not qualify as a specialty occupation",
      "Degree not directly related to the job duties (e.g., computer science degree for marketing role)",
      "LCA not certified or improperly completed",
      "Employer's ability to pay not sufficiently documented",
      "Educational credential evaluation not accepted",
      "H-1B cap subject — selected in lottery but application has issues",
    ],
    tips_for_strong_application: [
      "Use a detailed job description with specific duties matching specialty occupation criteria",
      "Provide a position-by-position degree requirement analysis linking education to role",
      "Include secondary evidence: organisation charts, SOC code analysis, industry standards",
      "For advanced degree exemption: ensure the degree is a US master's or higher, or equivalent",
      "Premium process I-140 concurrently if pursuing green card simultaneously",
    ],
    processing_time_estimate: "3–6 months standard; 15 business days with premium processing",
    premium_processing_available: true,
  },
  "L-1": {
    official_form: "I-129 (with L Classification Supplement)",
    filing_fee_note: "See fee_calculator tool for current USCIS fees",
    document_checklist: [
      "Form I-129 + L Supplement",
      "Evidence of qualifying relationship between US and foreign entity (org charts, financial statements, stock ownership)",
      "Beneficiary's employment history showing 1 continuous year abroad in last 3 years",
      "Job description for US position (managerial/executive for L-1A; specialised knowledge for L-1B)",
      "Job description for prior foreign position",
      "Performance reviews or employment verification letters",
      "Beneficiary's passport and prior immigration documents",
      "Petitioner financial evidence demonstrating ability to pay",
    ],
    common_denial_reasons: [
      "One-year abroad employment not continuous or not in qualifying capacity",
      "Managerial role does not involve managing people or a function (L-1A)",
      "Specialised knowledge claim not sufficiently distinguished from general skills (L-1B)",
      "Qualifying relationship between entities not clearly established",
    ],
    tips_for_strong_application: [
      "Document the organisational structure thoroughly — org charts with titles and head counts",
      "For L-1A: evidence that at least 2–3 employees are supervised, with decision-making authority shown",
      "For L-1B: specify the proprietary nature of the knowledge — systems, products, processes unique to the company",
      "Blanket L petitions (for large companies) streamline future L-1 filings",
    ],
    processing_time_estimate: "3–5 months; 15 business days with premium processing",
    premium_processing_available: true,
  },
  "O-1": {
    official_form: "I-129 (with O Classification Supplement)",
    filing_fee_note: "See fee_calculator tool for current USCIS fees",
    document_checklist: [
      "Form I-129 + O/P Supplement",
      "Advisory opinion from a relevant peer group or labour organisation (or explanation of why it is unavailable)",
      "Consultation letter",
      "Itinerary of activities or employment offer letter",
      "Evidence of extraordinary ability meeting at least 3 of 10 criteria (or 3 of 6 for arts O-1B):",
      "  — Major national/international prizes or awards",
      "  — Membership in associations requiring outstanding achievements",
      "  — Published material about the beneficiary's work",
      "  — Participation as a judge of others' work",
      "  — Original scientific, scholarly, artistic, or business contributions of major significance",
      "  — Authorship of scholarly articles in major publications",
      "  — Display of work at distinguished venues",
      "  — Critical or essential role in distinguished organisations",
      "  — High salary relative to peers",
      "  — Commercial successes in the performing arts",
      "Contracts, letters of recommendation from experts in the field",
    ],
    common_denial_reasons: [
      "Insufficient evidence — general letters without specifics",
      "Awards or publications not demonstrated to be prestigious at national/international level",
      "Judging or peer review not shown to be selective or recognised",
      "Salary comparator not properly documented",
    ],
    tips_for_strong_application: [
      "Quantity AND quality: more criteria partially met is less effective than fewer criteria strongly documented",
      "Expert recommendation letters should be from recognised authorities, not just colleagues",
      "Provide context: explain WHY an award or journal is prestigious",
      "Citation counts, h-index, and impact factor data are powerful for academic/research O-1A cases",
    ],
    processing_time_estimate: "2–3 months; 15 business days with premium processing",
    premium_processing_available: true,
  },
  "EB-1A": {
    official_form: "I-140 (Immigrant Petition for Alien Workers)",
    filing_fee_note: "See fee_calculator tool for current USCIS fees",
    document_checklist: [
      "Form I-140",
      "Evidence of extraordinary ability — must meet at least 3 of 10 criteria OR demonstrate a singular major achievement:",
      "  1. Receipt of national/international prizes or awards for excellence",
      "  2. Membership in associations requiring outstanding achievement",
      "  3. Published material in professional/major publications about the beneficiary",
      "  4. Judging the work of others in the field",
      "  5. Original scientific, scholarly, artistic, athletic, or business contributions of major significance",
      "  6. Authorship of scholarly articles in professional journals",
      "  7. Display of work at artistic exhibitions or showcases",
      "  8. Critical or essential role in distinguished organisations",
      "  9. High salary/remuneration in relation to others in the field",
      "  10. Commercial successes in performing arts",
      "Evidence of intent to continue work in the field of expertise",
      "Expert letters from recognised authorities",
      "If self-petitioning: statement of intent and field of endeavor",
    ],
    common_denial_reasons: [
      "Criteria met on their face but not at the level of extraordinary ability (must be among the few at the very top)",
      "Final merits determination: even if 3 criteria met, adjudicator may find overall evidence insufficient",
      "Letters too generic — do not address specific extraordinary contributions",
    ],
    tips_for_strong_application: [
      "After meeting initial criteria, prepare for final merits determination — provide a holistic narrative",
      "Respond to any RFE (Request for Evidence) meticulously — nearly all EB-1A denials come after RFE",
      "Consult an immigration attorney specialising in EB-1A — the standard is high and mistakes are costly",
    ],
    processing_time_estimate: "6–12 months standard; premium processing available for I-140",
    premium_processing_available: true,
  },
  "EB-1B": {
    official_form: "I-140",
    filing_fee_note: "See fee_calculator tool for current USCIS fees",
    document_checklist: [
      "Form I-140 filed by employer",
      "Evidence of international recognition for outstanding achievements in academic field",
      "At least 3 years of research or teaching experience",
      "Permanent research or tenured/tenure-track position offer",
      "Evidence meeting at least 2 of 6 criteria:",
      "  1. Major prizes or awards for outstanding achievement",
      "  2. Membership in associations requiring outstanding achievement",
      "  3. Published material in professional publications written by others about beneficiary's work",
      "  4. Participation as judge of the work of others in the field",
      "  5. Original scientific or scholarly research contributions to the field",
      "  6. Authorship of scholarly books or articles in journals with international circulation",
      "Recommendation letters from internationally recognised experts (NOT the petitioner)",
      "Beneficiary's CV, list of publications, citation record",
    ],
    common_denial_reasons: [
      "Position is not permanent (term appointments, visiting positions do not qualify)",
      "Only 2 criteria met but evidence is weak overall",
      "Letters from colleagues rather than independent internationally recognised experts",
    ],
    tips_for_strong_application: [
      "Independent citations are the strongest evidence — provide Google Scholar h-index and total citations",
      "Peer review invitations are powerful — document journals and their impact factors",
      "The permanence of the position is non-negotiable — ensure this is explicit in the job offer",
    ],
    processing_time_estimate: "6–12 months; premium processing available",
    premium_processing_available: true,
  },
  "EB-1C": {
    official_form: "I-140",
    filing_fee_note: "See fee_calculator tool for current USCIS fees",
    document_checklist: [
      "Form I-140 filed by US employer",
      "Evidence of one year continuous employment abroad in qualifying capacity in last 3 years",
      "Qualifying relationship between US and foreign entities",
      "Evidence that US position is managerial or executive in nature",
      "Organisational charts for both foreign and US entities",
      "Financial statements and tax returns demonstrating ability to pay",
      "Job descriptions for both prior and current roles",
      "Corporate documents (articles of incorporation, stock certificates)",
    ],
    common_denial_reasons: [
      "First-year operations — USCIS scrutinises new US entities without established track record",
      "Managerial capacity not clearly established — first-line supervisory only is insufficient",
      "Qualifying relationship not properly documented",
    ],
    tips_for_strong_application: [
      "For new US offices, file the L-1A first and build a track record before EB-1C",
      "Clearly distinguish managerial duties from operational duties in job description",
      "Show staff reporting to the beneficiary in org chart with number of employees",
    ],
    processing_time_estimate: "6–12 months; premium processing available",
    premium_processing_available: true,
  },
  "EB-2-NIW": {
    official_form: "I-140",
    filing_fee_note: "See fee_calculator tool for current USCIS fees",
    document_checklist: [
      "Form I-140 (self-petition)",
      "Evidence of advanced degree OR exceptional ability in the sciences, arts, or business",
      "For advanced degree: official transcripts, degree certificate, foreign evaluation if applicable",
      "For exceptional ability: meeting 3 of 6 criteria (degree, high salary, membership, recognition, etc.)",
      "Evidence meeting the three Dhirane prongs:",
      "  1. Proposed endeavor has substantial merit and national importance",
      "  2. Beneficiary is well-positioned to advance the proposed endeavor",
      "  3. Waiving the job offer and PERM requirement would benefit the US",
      "Expert recommendation letters from recognised authorities",
      "Evidence of prior contributions: publications, patents, citations, awards",
      "Detailed personal statement explaining the proposed endeavor and its national importance",
    ],
    common_denial_reasons: [
      "Proposed endeavor too broadly defined — must be specific and substantial",
      "National importance prong weak — must go beyond the individual's career",
      "Well-positioned prong: evidence of past achievements must predict future success",
    ],
    tips_for_strong_application: [
      "Hire an immigration attorney experienced in NIW — the three Dhirane prongs require a compelling narrative",
      "Specificity matters: 'AI research' is broad; 'developing neural interfaces for paralysis treatment in underserved populations' is concrete",
      "Strong citation record, patent filings, and adoption of your work by others are powerful supporting evidence",
    ],
    processing_time_estimate: "8–14 months; premium processing available",
    premium_processing_available: true,
  },
  "F-1": {
    official_form: "DS-160 (Nonimmigrant Visa Application) + I-20",
    filing_fee_note: "MRV fee $185; SEVIS fee $350 (most students) or $220 (vocational)",
    document_checklist: [
      "Form DS-160 completed online",
      "Valid passport (minimum 6 months beyond intended stay)",
      "Form I-20 issued by SEVP-certified school",
      "SEVIS fee payment receipt (Form I-901)",
      "US visa application fee receipt (MRV fee)",
      "Official acceptance letter from the school",
      "Evidence of financial support for full tuition and living expenses:",
      "  — Bank statements (3–6 months)",
      "  — Scholarship or assistantship award letter",
      "  — Sponsor affidavit with financial documentation",
      "Academic transcripts and diplomas from previous education",
      "Standardised test scores (TOEFL/IELTS, GRE, GMAT, etc.) if applicable",
      "Evidence of ties to home country (family, property, employment prospects)",
      "Resume or CV for graduate-level applicants",
    ],
    common_denial_reasons: [
      "Insufficient financial documentation — vague or unverified funds",
      "Failure to demonstrate non-immigrant intent (ties to home country)",
      "Inconsistency between stated purpose and academic field chosen",
      "Prior US visa denial not disclosed",
      "Prior status violations in the US",
    ],
    tips_for_strong_application: [
      "Be clear and concise in the visa interview — interviewers make decisions in under 2 minutes on average",
      "Have specific answers: why this school, this program, this career path",
      "Show a clear plan to return home: family, job offer in home country, property",
      "Bring all documents organised in a folder — even if not asked, preparedness signals legitimacy",
    ],
    processing_time_estimate: "Days to weeks at consulate; apply 3+ months before start date",
    premium_processing_available: false,
  },
  "K-1": {
    official_form: "I-129F (Petition for Alien Fiancé)",
    filing_fee_note: "I-129F: $675; DS-160 + MRV: $265; medical exam: $200–400",
    document_checklist: [
      "Form I-129F (filed by US citizen petitioner)",
      "Proof of US citizenship (passport, birth certificate, naturalisation certificate)",
      "Evidence of in-person meeting in last 2 years (photos, travel records, boarding passes)",
      "Evidence of genuine relationship (photos together, communications, call logs)",
      "Statement of intent to marry within 90 days of entry",
      "Evidence both parties are legally free to marry (divorce decrees if applicable)",
      "Petitioner's financial evidence (I-134 Affidavit of Support)",
      "Police certificates from each country where beneficiary has lived 6+ months (after age 16)",
      "Medical examination results (Form I-693 equivalent for immigrant visa)",
      "Biometrics appointment (beneficiary at US consulate)",
    ],
    common_denial_reasons: [
      "In-person meeting requirement not met (limited exceptions)",
      "Prior immigration violations by either party not disclosed",
      "Relationship not established as bona fide",
      "Petitioner income below 100% of Federal Poverty Guidelines",
    ],
    tips_for_strong_application: [
      "Document your relationship thoroughly — photo albums, WhatsApp/call logs, hotel receipts from visits",
      "The 90-day clock to marry starts on the K-1 entry date — do not delay",
      "After marriage, file I-485 for adjustment of status promptly",
      "Consulate interviews can be unpredictable — prepare both parties for potential questions about your relationship history",
    ],
    processing_time_estimate: "6–10 months from filing to entry",
    premium_processing_available: false,
  },
  "I-485": {
    official_form: "I-485 (Application to Register Permanent Residence)",
    filing_fee_note: "See fee_calculator tool for current USCIS fees",
    document_checklist: [
      "Form I-485",
      "Form I-864 Affidavit of Support (if family-based)",
      "Form I-944 (Declaration of Self-Sufficiency — check current USCIS requirements)",
      "Approved I-140 (employment) or approved I-130 (family) with current priority date",
      "Valid passport photos (2)",
      "Copy of passport biographical page",
      "Copy of birth certificate with certified translation",
      "Copy of marriage certificate (if applicable, with translation)",
      "Copy of divorce decree (if applicable)",
      "Form I-693 Medical Examination (within validity window)",
      "Form I-131 (Advance Parole) — highly recommended if international travel needed",
      "Form I-765 (Employment Authorization) — file concurrently",
      "2 years of tax returns (if required)",
      "Police certificates for each country lived 6+ months (age 16+)",
      "Any prior immigration court documents",
      "Evidence of lawful admission/maintenance of status",
    ],
    common_denial_reasons: [
      "Prior unlawful presence — bars to adjustment (INA 212(a)(9)(B))",
      "Prior removal or deportation order",
      "I-693 medical exam expired or outside validity window",
      "Affidavit of support below required income threshold",
      "Status violations — working without authorization, overstay",
    ],
    tips_for_strong_application: [
      "File I-131 (Advance Parole) concurrently — do NOT travel internationally until AP is approved",
      "File I-765 concurrently to maintain work authorisation during processing",
      "Respond to all RFEs within the stated deadline",
      "Track your case at uscis.gov/case-status regularly",
    ],
    processing_time_estimate: "8–24+ months depending on service center and visa category",
    premium_processing_available: false,
  },
  "naturalization": {
    official_form: "N-400 (Application for Naturalization)",
    filing_fee_note: "$760 filing fee ($85 biometrics — may be combined); fee waiver available for eligible applicants",
    document_checklist: [
      "Form N-400",
      "Copy of Permanent Resident Card (front and back)",
      "2 passport-style photos",
      "Copy of passport biographical page",
      "Evidence of continuous residence — tax returns, rent/mortgage records, utility bills",
      "Evidence of physical presence — travel records (I-94 history, passport stamps)",
      "If married to a US citizen: marriage certificate, proof of marriage",
      "If applicable: military service records, disability accommodation request",
      "Fee payment or fee waiver documentation",
    ],
    common_denial_reasons: [
      "Continuous residence broken by absences over 6 months (1+ year = presumption of abandonment)",
      "Failure to disclose criminal history — complete disclosure is required",
      "Failure to meet physical presence requirement (30 months in 5 years; 18 months in 3 years for LPR spouses)",
      "Outstanding tax obligations",
      "Failure of English or civics test",
    ],
    tips_for_strong_application: [
      "Study all 100 civics questions — you will be asked up to 10 and must answer 6 correctly",
      "Review your entire I-94 travel history at i94.cbp.dhs.gov",
      "Disclose ALL arrests, charges, and convictions — expunged records must also be disclosed",
      "File with an immigration attorney if you have ANY criminal history, even minor offences",
    ],
    processing_time_estimate: "8–24 months depending on field office",
    premium_processing_available: false,
  },
  "DACA": {
    official_form: "I-821D (Deferred Action for Childhood Arrivals) + I-765",
    filing_fee_note: "$495 (I-765 work permit); no DACA filing fee",
    document_checklist: [
      "Form I-821D (DACA request)",
      "Form I-765 (Employment Authorization Document request)",
      "Identity documents: passport, birth certificate (with translation), school records, military records",
      "Evidence of US presence since before June 15, 2007: school records, medical records, employment records, tax records, bank records",
      "Evidence of US residence on June 15, 2012",
      "Evidence of arrival under age 16",
      "School enrollment documentation or high school diploma/GED equivalent",
      "If served in military: DD-214 or military records",
      "2 passport photos",
    ],
    common_denial_reasons: [
      "Cannot establish continuous residence since before June 15, 2007",
      "Criminal history — certain offences disqualify; felonies and significant misdemeanours are bars",
      "Age requirements not met at time of filing",
      "Failure to demonstrate school enrollment or equivalent",
    ],
    tips_for_strong_application: [
      "Gather as many contemporaneous records as possible from the 2007–2012 period",
      "Consult an immigration attorney before applying if you have ANY criminal record",
      "Renew at least 5–6 months before expiration — DACA renewals have experienced processing delays",
    ],
    processing_time_estimate: "3–6 months for initial applications and renewals",
    premium_processing_available: false,
  },
  "TPS": {
    official_form: "I-821 (Application for Temporary Protected Status) + I-765",
    filing_fee_note: "$50 (I-821) + $410 (I-765); age-based reductions available",
    document_checklist: [
      "Form I-821",
      "Form I-765",
      "Passport or identity document from the TPS-designated country",
      "Evidence of nationality: birth certificate, passport, national identity card",
      "Evidence of US residence during the required period (varies by country-specific designation)",
      "Evidence of continuous physical presence since the TPS designation date",
      "2 passport photos",
      "For re-registration: prior TPS approval notice",
    ],
    common_denial_reasons: [
      "Not a national of a currently TPS-designated country",
      "Criminal bars — certain offences disqualify",
      "Failed to register during the initial registration period without a good cause exception",
    ],
    tips_for_strong_application: [
      "Register or re-register during the open registration period — missing it can be very difficult to correct",
      "Check uscis.gov for current TPS-designated countries and registration deadlines",
      "Consult an attorney if you have any criminal history",
    ],
    processing_time_estimate: "3–9 months",
    premium_processing_available: false,
  },
};

export function documentChecklist(input: z.infer<typeof DocumentChecklistInput>): string {
  const key = normKey(input.application_type);
  const profile = APPLICATION_PROFILES[input.application_type];

  const result = {
    application_type: input.application_type,
    primary_form: profile.official_form,
    processing_time_estimate: profile.processing_time_estimate,
    premium_processing_available: profile.premium_processing_available,
    document_checklist: profile.document_checklist.map((doc, i) => ({ item: i + 1, document: doc })),
    common_denial_reasons: profile.common_denial_reasons,
    tips_for_a_strong_application: profile.tips_for_strong_application,
    general_advice: [
      "Make TWO complete copies of everything before mailing — one to keep, one as a backup",
      "Use certified mail with return receipt when filing by paper",
      "Keep the original I-797 receipt notice in a safe place — it is proof of filing",
      "Respond to any RFE (Request for Evidence) within the stated deadline — extensions are rarely granted",
    ],
    key_resources: [
      "USCIS Forms: uscis.gov/forms",
      "USCIS Filing Fees: uscis.gov/fees",
      "USCIS Processing Times: uscis.gov/processing-times",
      "Find a licensed immigration attorney: ailalawyer.com or aila.org",
    ],
    disclaimer:
      "Document checklists are general guidance and may not reflect recent USCIS policy changes. Always verify current requirements at uscis.gov and consult a licensed immigration attorney.",
    generated_at: new Date().toISOString(),
  };

  return JSON.stringify(result, null, 2) + PROMO_FOOTER;
}
