// Deterministic hash-based heuristics for consistent, reproducible outputs

export function hash(input: string): number {
  let h = 5381;
  for (let i = 0; i < input.length; i++) {
    h = ((h << 5) + h + input.charCodeAt(i)) & 0x7fffffff;
  }
  return h;
}

export function seededRandom(seed: string, index = 0): number {
  const h = hash(`${seed}:${index}`);
  return (h % 10000) / 10000;
}

export function pick<T>(arr: T[], seed: string, index = 0): T {
  return arr[hash(`${seed}:${index}`) % arr.length];
}

export function pickN<T>(arr: T[], n: number, seed: string): T[] {
  const shuffled = [...arr].sort((a, b) => hash(`${seed}:${String(a)}`) - hash(`${seed}:${String(b)}`));
  return shuffled.slice(0, n);
}

export function rangeInt(min: number, max: number, seed: string, index = 0): number {
  return min + (hash(`${seed}:${index}`) % (max - min + 1));
}

export function rangeFloat(min: number, max: number, seed: string, index = 0): number {
  return min + seededRandom(seed, index) * (max - min);
}

export const FOOTER = `\n---\n🥗 Want automated weekly meal plans? mama.oliwoods.com/beta`;

// ── Meal Planning Domain Data ────────────────────────────────────────────────

export interface Recipe {
  name: string;
  cuisine: string;
  diet_tags: string[];
  prep_minutes: number;
  cook_minutes: number;
  servings: number;
  calories_per_serving: number;
  protein_g: number;
  carbs_g: number;
  fat_g: number;
  ingredients: string[];
  difficulty: "easy" | "medium" | "hard";
}

export const RECIPE_DB: Recipe[] = [
  // ── Breakfast ─────────────────────────────────────────────────────────────
  {
    name: "Greek Yogurt Parfait",
    cuisine: "Mediterranean",
    diet_tags: ["vegetarian", "gluten-free"],
    prep_minutes: 5,
    cook_minutes: 0,
    servings: 1,
    calories_per_serving: 320,
    protein_g: 22,
    carbs_g: 40,
    fat_g: 7,
    ingredients: ["greek yogurt", "mixed berries", "granola", "honey", "chia seeds"],
    difficulty: "easy",
  },
  {
    name: "Avocado Toast with Poached Eggs",
    cuisine: "American",
    diet_tags: ["vegetarian"],
    prep_minutes: 10,
    cook_minutes: 8,
    servings: 2,
    calories_per_serving: 380,
    protein_g: 18,
    carbs_g: 32,
    fat_g: 22,
    ingredients: ["sourdough bread", "avocado", "eggs", "lemon", "red pepper flakes", "sea salt"],
    difficulty: "easy",
  },
  {
    name: "Overnight Oats with Almond Butter",
    cuisine: "American",
    diet_tags: ["vegetarian", "vegan"],
    prep_minutes: 5,
    cook_minutes: 0,
    servings: 1,
    calories_per_serving: 420,
    protein_g: 14,
    carbs_g: 58,
    fat_g: 16,
    ingredients: ["rolled oats", "almond milk", "almond butter", "banana", "maple syrup", "cinnamon"],
    difficulty: "easy",
  },
  {
    name: "Veggie Omelette",
    cuisine: "American",
    diet_tags: ["vegetarian", "gluten-free", "keto"],
    prep_minutes: 10,
    cook_minutes: 8,
    servings: 1,
    calories_per_serving: 290,
    protein_g: 24,
    carbs_g: 8,
    fat_g: 18,
    ingredients: ["eggs", "bell pepper", "spinach", "mushrooms", "cheddar cheese", "olive oil"],
    difficulty: "easy",
  },
  {
    name: "Shakshuka",
    cuisine: "Mediterranean",
    diet_tags: ["vegetarian", "gluten-free"],
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 2,
    calories_per_serving: 310,
    protein_g: 18,
    carbs_g: 28,
    fat_g: 14,
    ingredients: ["eggs", "canned tomatoes", "bell peppers", "onion", "garlic", "cumin", "paprika", "feta cheese"],
    difficulty: "medium",
  },
  {
    name: "Smoothie Bowl",
    cuisine: "American",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 1,
    calories_per_serving: 360,
    protein_g: 10,
    carbs_g: 64,
    fat_g: 9,
    ingredients: ["frozen acai", "frozen banana", "almond milk", "granola", "coconut flakes", "kiwi", "blueberries"],
    difficulty: "easy",
  },
  {
    name: "Keto Bacon and Egg Cups",
    cuisine: "American",
    diet_tags: ["gluten-free", "keto", "paleo"],
    prep_minutes: 5,
    cook_minutes: 20,
    servings: 2,
    calories_per_serving: 340,
    protein_g: 26,
    carbs_g: 2,
    fat_g: 26,
    ingredients: ["bacon", "eggs", "cheddar cheese", "chives", "black pepper"],
    difficulty: "easy",
  },
  {
    name: "Chia Pudding with Mango",
    cuisine: "American",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 5,
    cook_minutes: 0,
    servings: 1,
    calories_per_serving: 280,
    protein_g: 8,
    carbs_g: 42,
    fat_g: 10,
    ingredients: ["chia seeds", "coconut milk", "mango", "lime juice", "agave nectar"],
    difficulty: "easy",
  },
  // ── Lunch ──────────────────────────────────────────────────────────────────
  {
    name: "Mediterranean Quinoa Salad",
    cuisine: "Mediterranean",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories_per_serving: 340,
    protein_g: 12,
    carbs_g: 48,
    fat_g: 13,
    ingredients: ["quinoa", "cucumber", "cherry tomatoes", "kalamata olives", "red onion", "feta cheese", "fresh mint", "lemon dressing"],
    difficulty: "easy",
  },
  {
    name: "Chicken Caesar Wrap",
    cuisine: "American",
    diet_tags: [],
    prep_minutes: 15,
    cook_minutes: 12,
    servings: 2,
    calories_per_serving: 480,
    protein_g: 38,
    carbs_g: 42,
    fat_g: 17,
    ingredients: ["grilled chicken breast", "romaine lettuce", "whole wheat tortilla", "parmesan", "caesar dressing", "croutons"],
    difficulty: "easy",
  },
  {
    name: "Lentil Soup",
    cuisine: "Mediterranean",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 15,
    cook_minutes: 35,
    servings: 6,
    calories_per_serving: 260,
    protein_g: 16,
    carbs_g: 42,
    fat_g: 4,
    ingredients: ["red lentils", "carrots", "celery", "onion", "garlic", "cumin", "coriander", "vegetable broth", "lemon juice"],
    difficulty: "easy",
  },
  {
    name: "Spicy Tuna Poke Bowl",
    cuisine: "Asian",
    diet_tags: ["gluten-free"],
    prep_minutes: 20,
    cook_minutes: 20,
    servings: 2,
    calories_per_serving: 520,
    protein_g: 36,
    carbs_g: 58,
    fat_g: 14,
    ingredients: ["sushi-grade tuna", "sushi rice", "avocado", "edamame", "cucumber", "sriracha mayo", "soy sauce", "sesame oil", "sesame seeds"],
    difficulty: "medium",
  },
  {
    name: "Black Bean Tacos",
    cuisine: "Mexican",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 10,
    cook_minutes: 15,
    servings: 4,
    calories_per_serving: 320,
    protein_g: 14,
    carbs_g: 50,
    fat_g: 8,
    ingredients: ["black beans", "corn tortillas", "avocado", "salsa", "lime", "cilantro", "red cabbage", "jalapeño"],
    difficulty: "easy",
  },
  {
    name: "Caprese Panini",
    cuisine: "Italian",
    diet_tags: ["vegetarian"],
    prep_minutes: 10,
    cook_minutes: 8,
    servings: 2,
    calories_per_serving: 430,
    protein_g: 20,
    carbs_g: 44,
    fat_g: 20,
    ingredients: ["ciabatta bread", "fresh mozzarella", "tomato", "fresh basil", "balsamic glaze", "olive oil"],
    difficulty: "easy",
  },
  {
    name: "Thai Green Curry Soup",
    cuisine: "Asian",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 15,
    cook_minutes: 25,
    servings: 4,
    calories_per_serving: 380,
    protein_g: 10,
    carbs_g: 44,
    fat_g: 20,
    ingredients: ["coconut milk", "green curry paste", "tofu", "zucchini", "bell peppers", "rice noodles", "lime leaves", "thai basil"],
    difficulty: "medium",
  },
  // ── Dinner ─────────────────────────────────────────────────────────────────
  {
    name: "Grilled Salmon with Asparagus",
    cuisine: "Mediterranean",
    diet_tags: ["gluten-free", "paleo", "keto"],
    prep_minutes: 10,
    cook_minutes: 20,
    servings: 2,
    calories_per_serving: 520,
    protein_g: 46,
    carbs_g: 12,
    fat_g: 32,
    ingredients: ["salmon fillet", "asparagus", "lemon", "garlic", "olive oil", "fresh dill", "capers"],
    difficulty: "easy",
  },
  {
    name: "Chicken Tikka Masala",
    cuisine: "Asian",
    diet_tags: ["gluten-free"],
    prep_minutes: 20,
    cook_minutes: 40,
    servings: 4,
    calories_per_serving: 460,
    protein_g: 38,
    carbs_g: 24,
    fat_g: 22,
    ingredients: ["chicken breast", "heavy cream", "canned tomatoes", "onion", "garlic", "ginger", "garam masala", "turmeric", "cumin", "basmati rice"],
    difficulty: "medium",
  },
  {
    name: "Spaghetti Bolognese",
    cuisine: "Italian",
    diet_tags: [],
    prep_minutes: 15,
    cook_minutes: 45,
    servings: 4,
    calories_per_serving: 580,
    protein_g: 34,
    carbs_g: 62,
    fat_g: 20,
    ingredients: ["spaghetti", "ground beef", "canned tomatoes", "onion", "garlic", "carrot", "celery", "red wine", "parmesan"],
    difficulty: "medium",
  },
  {
    name: "Veggie Stir-Fry with Tofu",
    cuisine: "Asian",
    diet_tags: ["vegetarian", "vegan"],
    prep_minutes: 20,
    cook_minutes: 15,
    servings: 3,
    calories_per_serving: 340,
    protein_g: 18,
    carbs_g: 38,
    fat_g: 14,
    ingredients: ["firm tofu", "broccoli", "snap peas", "carrots", "bell pepper", "soy sauce", "sesame oil", "ginger", "garlic", "jasmine rice"],
    difficulty: "easy",
  },
  {
    name: "Beef Tacos",
    cuisine: "Mexican",
    diet_tags: ["gluten-free"],
    prep_minutes: 15,
    cook_minutes: 20,
    servings: 4,
    calories_per_serving: 480,
    protein_g: 32,
    carbs_g: 38,
    fat_g: 22,
    ingredients: ["ground beef", "corn tortillas", "taco seasoning", "shredded cheddar", "sour cream", "salsa", "lettuce", "tomato"],
    difficulty: "easy",
  },
  {
    name: "Eggplant Parmesan",
    cuisine: "Italian",
    diet_tags: ["vegetarian"],
    prep_minutes: 20,
    cook_minutes: 45,
    servings: 4,
    calories_per_serving: 420,
    protein_g: 20,
    carbs_g: 44,
    fat_g: 18,
    ingredients: ["eggplant", "marinara sauce", "mozzarella", "parmesan", "breadcrumbs", "eggs", "fresh basil", "olive oil"],
    difficulty: "medium",
  },
  {
    name: "Sheet Pan Chicken Thighs with Vegetables",
    cuisine: "American",
    diet_tags: ["gluten-free", "paleo"],
    prep_minutes: 15,
    cook_minutes: 40,
    servings: 4,
    calories_per_serving: 490,
    protein_g: 40,
    carbs_g: 28,
    fat_g: 24,
    ingredients: ["chicken thighs", "broccoli", "sweet potato", "red onion", "olive oil", "garlic powder", "paprika", "rosemary"],
    difficulty: "easy",
  },
  {
    name: "Shrimp Fajitas",
    cuisine: "Mexican",
    diet_tags: ["gluten-free"],
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 3,
    calories_per_serving: 420,
    protein_g: 30,
    carbs_g: 46,
    fat_g: 14,
    ingredients: ["shrimp", "bell peppers", "onion", "corn tortillas", "lime", "cumin", "chili powder", "garlic", "avocado"],
    difficulty: "easy",
  },
  {
    name: "Lamb Kofta with Tabbouleh",
    cuisine: "Mediterranean",
    diet_tags: ["paleo"],
    prep_minutes: 25,
    cook_minutes: 20,
    servings: 4,
    calories_per_serving: 540,
    protein_g: 36,
    carbs_g: 30,
    fat_g: 30,
    ingredients: ["ground lamb", "parsley", "bulgur wheat", "tomatoes", "cucumber", "mint", "lemon", "cumin", "coriander", "onion"],
    difficulty: "medium",
  },
  {
    name: "Mushroom Risotto",
    cuisine: "Italian",
    diet_tags: ["vegetarian", "gluten-free"],
    prep_minutes: 15,
    cook_minutes: 35,
    servings: 4,
    calories_per_serving: 460,
    protein_g: 14,
    carbs_g: 66,
    fat_g: 16,
    ingredients: ["arborio rice", "mixed mushrooms", "parmesan", "white wine", "vegetable broth", "shallots", "garlic", "butter", "fresh thyme"],
    difficulty: "hard",
  },
  {
    name: "Pork Tenderloin with Apple Slaw",
    cuisine: "American",
    diet_tags: ["gluten-free", "paleo"],
    prep_minutes: 20,
    cook_minutes: 30,
    servings: 4,
    calories_per_serving: 430,
    protein_g: 44,
    carbs_g: 22,
    fat_g: 18,
    ingredients: ["pork tenderloin", "apple", "cabbage", "dijon mustard", "apple cider vinegar", "honey", "celery seed", "olive oil"],
    difficulty: "medium",
  },
  {
    name: "Cauliflower Fried Rice",
    cuisine: "Asian",
    diet_tags: ["vegetarian", "vegan", "gluten-free", "keto", "paleo"],
    prep_minutes: 15,
    cook_minutes: 15,
    servings: 4,
    calories_per_serving: 220,
    protein_g: 10,
    carbs_g: 18,
    fat_g: 12,
    ingredients: ["cauliflower", "eggs", "carrots", "peas", "soy sauce", "sesame oil", "garlic", "ginger", "green onions"],
    difficulty: "easy",
  },
  // ── Snacks ─────────────────────────────────────────────────────────────────
  {
    name: "Hummus with Veggie Sticks",
    cuisine: "Mediterranean",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 5,
    cook_minutes: 0,
    servings: 2,
    calories_per_serving: 180,
    protein_g: 7,
    carbs_g: 22,
    fat_g: 8,
    ingredients: ["hummus", "carrots", "celery", "cucumber", "bell pepper"],
    difficulty: "easy",
  },
  {
    name: "Apple Slices with Peanut Butter",
    cuisine: "American",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 5,
    cook_minutes: 0,
    servings: 1,
    calories_per_serving: 230,
    protein_g: 8,
    carbs_g: 30,
    fat_g: 10,
    ingredients: ["apple", "peanut butter"],
    difficulty: "easy",
  },
  {
    name: "Mixed Nuts and Dried Fruit",
    cuisine: "American",
    diet_tags: ["vegetarian", "vegan", "gluten-free", "paleo"],
    prep_minutes: 2,
    cook_minutes: 0,
    servings: 1,
    calories_per_serving: 200,
    protein_g: 6,
    carbs_g: 20,
    fat_g: 12,
    ingredients: ["almonds", "walnuts", "cashews", "dried cranberries", "raisins"],
    difficulty: "easy",
  },
  {
    name: "Guacamole with Tortilla Chips",
    cuisine: "Mexican",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 4,
    calories_per_serving: 210,
    protein_g: 3,
    carbs_g: 24,
    fat_g: 12,
    ingredients: ["avocados", "lime juice", "cilantro", "jalapeño", "red onion", "tomato", "tortilla chips"],
    difficulty: "easy",
  },
  {
    name: "Caprese Skewers",
    cuisine: "Italian",
    diet_tags: ["vegetarian", "gluten-free", "keto"],
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 4,
    calories_per_serving: 160,
    protein_g: 10,
    carbs_g: 4,
    fat_g: 12,
    ingredients: ["cherry tomatoes", "fresh mozzarella", "fresh basil", "balsamic glaze", "olive oil"],
    difficulty: "easy",
  },
  {
    name: "Edamame with Sea Salt",
    cuisine: "Asian",
    diet_tags: ["vegetarian", "vegan", "gluten-free", "keto"],
    prep_minutes: 2,
    cook_minutes: 5,
    servings: 2,
    calories_per_serving: 120,
    protein_g: 11,
    carbs_g: 10,
    fat_g: 5,
    ingredients: ["edamame", "sea salt"],
    difficulty: "easy",
  },
  {
    name: "Greek Yogurt with Honey and Walnuts",
    cuisine: "Mediterranean",
    diet_tags: ["vegetarian", "gluten-free"],
    prep_minutes: 3,
    cook_minutes: 0,
    servings: 1,
    calories_per_serving: 220,
    protein_g: 14,
    carbs_g: 20,
    fat_g: 10,
    ingredients: ["greek yogurt", "honey", "walnuts", "cinnamon"],
    difficulty: "easy",
  },
  {
    name: "Rice Cakes with Almond Butter and Banana",
    cuisine: "American",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 5,
    cook_minutes: 0,
    servings: 1,
    calories_per_serving: 190,
    protein_g: 5,
    carbs_g: 32,
    fat_g: 6,
    ingredients: ["rice cakes", "almond butter", "banana", "cinnamon"],
    difficulty: "easy",
  },
  {
    name: "Keto Fat Bombs",
    cuisine: "American",
    diet_tags: ["vegetarian", "gluten-free", "keto"],
    prep_minutes: 10,
    cook_minutes: 0,
    servings: 6,
    calories_per_serving: 160,
    protein_g: 4,
    carbs_g: 2,
    fat_g: 16,
    ingredients: ["cream cheese", "peanut butter", "coconut oil", "cocoa powder", "sweetener"],
    difficulty: "easy",
  },
  {
    name: "Spiced Roasted Chickpeas",
    cuisine: "Mediterranean",
    diet_tags: ["vegetarian", "vegan", "gluten-free"],
    prep_minutes: 5,
    cook_minutes: 30,
    servings: 4,
    calories_per_serving: 170,
    protein_g: 8,
    carbs_g: 26,
    fat_g: 4,
    ingredients: ["chickpeas", "olive oil", "cumin", "paprika", "garlic powder", "cayenne"],
    difficulty: "easy",
  },
  {
    name: "Cucumber Rolls with Cream Cheese and Smoked Salmon",
    cuisine: "American",
    diet_tags: ["gluten-free", "keto"],
    prep_minutes: 15,
    cook_minutes: 0,
    servings: 2,
    calories_per_serving: 140,
    protein_g: 12,
    carbs_g: 4,
    fat_g: 9,
    ingredients: ["cucumber", "cream cheese", "smoked salmon", "dill", "capers"],
    difficulty: "easy",
  },
];

export const GROCERY_CATEGORIES = [
  "Produce",
  "Meat & Seafood",
  "Dairy & Eggs",
  "Grains & Bread",
  "Canned Goods & Dry Pantry",
  "Frozen",
  "Spices & Condiments",
  "Beverages",
  "Snacks",
];

export const SPICE_STAPLES = [
  "olive oil",
  "kosher salt",
  "black pepper",
  "garlic powder",
  "onion powder",
  "cumin",
  "paprika",
  "chili powder",
  "dried oregano",
  "dried thyme",
  "red pepper flakes",
  "cinnamon",
  "turmeric",
  "soy sauce",
  "apple cider vinegar",
  "chicken broth",
  "vegetable broth",
  "canned tomatoes",
  "dijon mustard",
  "hot sauce",
];

export const PREP_TECHNIQUES = [
  "Batch cook grains (rice, quinoa) — make 3–4 cups at once, store in airtight container",
  "Roast a sheet pan of vegetables — toss in olive oil and seasoning, roast at 425°F for 25 min",
  "Hard-boil a dozen eggs — keeps up to 1 week in the refrigerator",
  "Marinate proteins overnight — deepens flavor, reduces weeknight prep time",
  "Chop all onions and garlic at once — store in airtight containers for up to 3 days",
  "Pre-wash and spin-dry salad greens — keeps fresh for 4–5 days wrapped in paper towels",
  "Portion snacks into individual containers — reduces decision fatigue during the week",
  "Make a large batch of sauce or dressing — use across multiple meals",
  "Brown and season ground meat — freeze in portions for quick weeknight meals",
  "Pre-cut fruit for smoothie bags — freeze to use as needed",
];
